random_seed: 0
structure_type: tower
generator_model_dir: /home/weiyu/Research/intern/semantic-rearrangement/models/actor_vae_language_all_shapes_new_stacking/best_model
data_split: train
data_root: /home/weiyu/data_drive/physics_eval_1016/vae_stacking
assets_path: /home/weiyu/Research/intern/brain_gym/assets/urdf
object_model_dir: /home/weiyu/data_drive/structformer_assets/housekeep_custom_handpicked_small
redirect_stdout: True
shuffle: False
max_num_eval: 100
visualize: False
override_data_dirs:
  - /home/weiyu/data_drive/data_housekeep_custom/tower/result
override_index_dirs:
  - index