random_seed: ${base.random_seed}
structure_type: line
generator_model_dir: ${base.models.transformer.line}
data_split: train
data_root: ${base.dirs.experiment}/transformer_line
assets_path: ${base.assets_path}
object_model_dir: ${base.object_model_dir}
redirect_stdout: ${base.redirect_stdout}
shuffle: False
max_num_eval: ${base.max_num_eval}
visualize: ${base.visualize}
override_data_dirs:
  - ${base.dirs.data}/line/result
override_index_dirs:
  - index