random_seed: 0
structure_type: tower
generator_model_dir: ${base.models.diffusion}
data_split: train
data_root: ${base.dirs.experiment}/diffusion_tower
assets_path: ${base.assets_path}
object_model_dir: ${base.object_model_dir}
redirect_stdout: ${base.redirect_stdout}
shuffle: False
max_num_eval: ${base.max_num_eval}
visualize: ${base.visualize}
override_data_dirs:
  - ${base.dirs.data}/tower/result
override_index_dirs:
  - index