random_seed: 0
structure_type: line
generator_model_dir: /home/weiyu/Research/intern/StructDiffuser/experiments/20220903-222727/model
data_split: train
data_root: /home/weiyu/data_drive/physics_eval_0914/diffuser_line
assets_path: /home/weiyu/Research/intern/brain_gym/assets/urdf
object_model_dir: /home/weiyu/Research/intern/brain_gym/data/acronym_handpicked_v4
redirect_stdout: True
shuffle: False
max_num_eval: 100
visualize: False
override_data_dirs:
  - /home/weiyu/data_drive/data_test_objects/line_data/result
override_index_dirs:
  - index