base:
  dirs:
    # base dir for physics evaluation
    experiment:  /home/weiyu/data_drive/physics_eval_0406
    # where the testing scene is stored
    data: /home/weiyu/data_drive/StructDiffusion/testing_data
  # dirs for the trained models
  models:
    diffusion: /home/weiyu/data_drive/StructDiffuser/experiments/20220903-222727/model
    diffusion_lang_template: /media/weiyu/T71/StructFormerDiffusion/StructDiffuser/experiments/20220908-153226/model
    collision: /home/weiyu/data_drive/StructDiffusion/models/collision/best_model
    discriminator: /home/weiyu/data_drive/StructDiffusion/models/structure_discriminator/best_model
    vae: /home/weiyu/data_drive/semantic-rearrangement/models/actor_vae_language_all_shapes_new_stacking/best_model
    transformer:
      circle: /home/weiyu/data_drive/StructDiffusion/models/transformer_circle/best_model
      dinner: /home/weiyu/data_drive/StructDiffusion/models/transformer_dinner/best_model
      line: /home/weiyu/data_drive/StructDiffusion/models/transformer_line/best_model
      tower: /home/weiyu/data_drive/StructDiffusion/models/transformer_stacking/best_model
  # urdfs for the environment and robot, included in the rearrangement_gym repo
  assets_path: /home/weiyu/Research/StructDiffusion/rearrangement_gym/assets/urdf
  # where the object models are stored
  object_model_dir: /home/weiyu/data_drive/StructDiffusion/housekeep_custom_handpicked_small
  # whether to log evaluation info to a file. Set this to True for batch evaluation.
  redirect_stdout: True
  # the number of scenes that will be tested
  max_num_eval: 100
  # whether to visualize prediction. Set this to False for batch evaluation.
  visualize: False
  random_seed: 0
  rejection:
    num_samples: 100
  cem:
    num_iteration: 10
    num_samples: 500
    num_elite: 10
    num_best_so_far: 1