base_dirs:
  # needed quick start
  testing_data: /path/to/testing_data
  wandb_dir: /path/to/wandb_logs
  # needed for training diffusion
  data: /path/to/training_data
  # needed for training collision discriminator
  pairwise_collision_data: /path/to/pairwise_collision_data
  # needed for evaluation in physics sim
  # assets_dir: /path/to/acronym_handpicked_large
  # experiment: /path/to/experiments