base_dirs:
  # needed quick start
  testing_data: "/media/exx/T7 Shield/ICLR23/SFormer-original/StructFormer/data_new_objects_test_split"
  wandb_dir: "/media/exx/T7 Shield/ICLR23/SFormer-original/StructDiffusion/wandb_logs"
  # needed for training diffusion
  data: /path/to/training_data
  # needed for training collision discriminator
  pairwise_collision_data: /path/to/pairwise_collision_data
  # needed for evaluation in physics sim
  # assets_dir: /path/to/acronym_handpicked_large
  # experiment: /path/to/experiments