base_dirs:
  # a new dir will be created for each training run
  experiment: /home/weiyu/data_drive/StructDiffusion/experiments
  # where the training data is stored
  data: /home/weiyu/data_drive/StructDiffusion/training_data