experiment_dir: ${base_dirs.experiment}/${env:DATETIME}

random_seed: 1
device: 0

save_model: True
save_best_model: True

dataset:
  dirs:
    - ${base_dirs.data}/examples_circle_new_objects/result
    - ${base_dirs.data}/examples_line_new_objects/result
    - ${base_dirs.data}/examples_stacking_new_objects/result
    - ${base_dirs.data}/examples_dinner_new_objects/result
  index_dirs:
    - index_10k
    - index_10k
    - index_10k
    - index_10k
  vocab_dir: ${base_dirs.data}/type_vocabs_coarse.json
  batch_size: 128
  max_num_objects: 7
  max_num_other_objects: 5
  max_num_shape_parameters: 5
  max_num_rearrange_features: 0
  max_num_anchor_features: 0
  num_pts: 1024
  filter_num_moved_objects_range:
  num_workers: 8
  pin_memory: True

model:
  name: transformer_diffuser_lang
  num_attention_heads: 8
  encoder_hidden_dim: 512
  encoder_dropout: 0.0
  encoder_activation: relu
  encoder_num_layers: 8
  structure_dropout: 0
  object_dropout: 0
  ignore_rgb: True

training:
  learning_rate: 0.0001
  max_epochs: 200
  l2: 0  #0.0001
  # lr_restart: 3000
  # warmup: 10

diffusion:
  time_steps: 200
  loss_type: huber