random_seed: ${base.random_seed}
structure_type: circle
generator_model_dir: ${base.models.transformer.circle}
data_split: train
data_root: ${base.dirs.experiment}/transformer_circle_discriminator_cem
discriminator_model_dir: ${base.models.discriminator}
collision_score_weight: 0.0
discriminator_score_weight: 1.0
ce_num_iteration: ${base.cem.num_iteration}
ce_num_samples: ${base.cem.num_samples}
ce_num_elite: ${base.cem.num_elite}
ce_num_best_so_far: ${base.cem.num_best_so_far}
discriminator_inference_batch_size: 64
assets_path: ${base.assets_path}
object_model_dir: ${base.object_model_dir}
redirect_stdout: ${base.redirect_stdout}
shuffle: False
max_num_eval: ${base.max_num_eval}
visualize: ${base.visualize}
override_data_dirs:
  - ${base.dirs.data}/circle/result
override_index_dirs:
  - index