random_seed: 0
structure_type: dinner
generator_model_dir: /home/weiyu/Research/intern/semantic-rearrangement/models/actor_vae_language_all_shapes_new_stacking/best_model
data_split: train
data_root: /home/weiyu/data_drive/physics_eval_0914/vae_dinner
assets_path: /home/weiyu/Research/intern/brain_gym/assets/urdf
object_model_dir: /home/weiyu/Research/intern/brain_gym/data/acronym_handpicked_v4
redirect_stdout: True
shuffle: False
max_num_eval: 100
visualize: False
override_data_dirs:
  - /home/weiyu/data_drive/data_test_objects/dinner_data/result
override_index_dirs:
  - index