random_seed: ${base.random_seed}
structure_type: line
generator_model_dir: ${base.models.transformer.line}
data_split: train
data_root: ${base.dirs.experiment}/transformer_line_collision
collision_model_dir: ${base.models.collision}
collision_score_weight: 1.0
discriminator_score_weight: 0.0
num_samples: ${base.rejection.num_samples}
num_elite: 1
discriminator_inference_batch_size: 20
assets_path: ${base.assets_path}
object_model_dir: ${base.object_model_dir}
redirect_stdout: ${base.redirect_stdout}
shuffle: False
max_num_eval: ${base.max_num_eval}
visualize: ${base.visualize}
override_data_dirs:
  - ${base.dirs.data}/line/result
override_index_dirs:
  - index